POST http://localhost:7000/api/users/register HTTP/1.1
content-type: application/json

{
      "email":"a4c23232@gmail.com",
      "password":"123456789",
      "firstName":"Tax",
      "lastName":"khedr"
     
}
###

POST http://localhost:7000/api/auth/login HTTP/1.1
content-type: application/json

{
      "email":"fake@gmail.com",
      "password":"12345678"
}

###

GET http://localhost:7000/api/my-hotels HTTP/1.1
content-type: application/json

{
        "userId": "687b5bb9ca4aa3689febdf5b"
}

###


###
POST http://localhost:7000/api/my-hotels HTTP/1.1
content-type: application/json

{
        "userId": "687a2dfeb392ea151a41e403",
        "name":"JW-Merriot Hotel",
        "city":"Mumbai",
        "country":"India",
        "description":"fabulous ,dont vary about facilities",
        "type":"AC/NON AC",
        "adultCount":"3",
        "childCount":"5",
        "facilities":"with attach bath and swimming pool",
        "pricePerNight":"24000",
        "starRating":"4",
        "imageUrls":["https://up.yimg.com/ib/th/id/OIP.oa6wkUpT9KjcmuimacYq3gHaE6?pid=Api&rs=1&c=1&qlt=95&w=151&h=100"],
        
}

###

DELETE  http://localhost:7000/api/my-hotels/68844d69299398bca85fc72e HTTP/1.1
Content-Type: application/json

{
            
}

###

PUT http://localhost:7000/api/my-hotels/688377a65eeb0ca3bbe09acf HTTP/1.1
Content-Type: application/json

{
       
          "name": "JW M",
          "city": "pune",
          "country": "India",
          "description": "unique larget majistique Hotel",
          "type": "Bussiness"
    
}

###

GET http://localhost:7000/api/hotels/search?page=1 HTTP/1.1
Content-Type: application/json

{
      
}

### 

GET http://localhost:7000/api/hotels/688af9babfd841ba42a926ae HTTP/1.1
Content-Type: application/json

{
      
}